1-D Array

In [1]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
x.ndim #1 dimensional
print(x.shape) #(number of vlue(1-n),)

[1 2 3 4 5]
(5,)


2-D Array

In [17]:
x=[[1,2,3,54],[4,5,6,67],[7,8,9,57]]
x1=np.array(x)
print(x1)
print(x1.ndim)       # 2 - dimension
print(x1.shape)      #(row,col)
print(x1.shape[0])   #retrieves row of array
print(x1[0:,2])      #[3 6 9]
print(x1[0,0:])      #[1 2 3 54]
print(x1[0:,0::2])   #[[1 3] [4 6] [7 9]]
print(x1[0:2,1::2])  #[[ 2 54] [ 5 67]]
print(x1[1:,0:2])    #[[4 5] [7 8]]

[[ 1  2  3 54]
 [ 4  5  6 67]
 [ 7  8  9 57]]
2
(3, 4)
3
[3 6 9]
[ 1  2  3 54]
[[1 3]
 [4 6]
 [7 9]]
[[ 2 54]
 [ 5 67]]
[[4 5]
 [7 8]]


3-D Array

In [24]:
x=[[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]]
x1=np.array(x)
print(x1)
print("----------------------")
print(x1.ndim)          # 3 - dimension
print("----------------------")
print(x1.shape)         #(number of 2D list,row,col)
print("----------------------")
print(x1[0,1,2])        #6
print("----------------------")
print(x1[0,2,0:])       #[7 8 9]
print("----------------------")
print(x1[0:,2,0:])      #[[7 8 9] [17 18 19]]
print("----------------------")
print(x1[0:,0::2,0::2]) #[[[ 1  3] [ 7  9]]  [[11 13] [17 19]]]
print("----------------------")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
----------------------
3
----------------------
(2, 3, 3)
----------------------
6
----------------------
[7 8 9]
----------------------
[[ 7  8  9]
 [17 18 19]]
----------------------
[[[ 1  3]
  [ 7  9]]

 [[11 13]
  [17 19]]]
----------------------


Re-Shaping

In [32]:
z=np.arange(1,101)
x=np.array(z)
print(x)
#1-D to 2-D
#print(x.reshape(10,-1)) 1 unknown axis(a,b) works until it can subcreate the other
#print(x.reshape(10,10))
print("------------------------------------------------------------------------------")
#1-D to 3-D
print(x.reshape(2,2,25))

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
----------------------
[[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
    18  19  20  21  22  23  24  25]
  [ 26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42
    43  44  45  46  47  48  49  50]]

 [[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
    68  69  70  71  72  73  74  75]
  [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
    93  94  95  96  97  98  99 100]]]


Concatination

In [37]:
x=[[1,2,3],[4,5,6],[7,8,9]]
y=[[11,12,13],[14,15,16],[17,18,19]]
x1=np.array(x)
y1=np.array(y)
z=np.concatenate((x1,y1),axis=0)  #Add by rows
print(z)
z1=np.concatenate((x1,y1),axis=1) #Add by Columns
print(z1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


Array Split

In [41]:
z=np.arange(1,11)
x=np.array(z)
s=np.array_split(z,3)
#print(s)     [array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]
s1=np.array_split(z,6)
#print(s1)     [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9]), array([10])]


[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9]), array([10])]


where and sort

In [2]:
l1=[2,5,22,45,56,23,11,23,6,18,19,35]
x1=np.array(l1)
print(x1)

[ 2  5 22 45 56 23 11 23  6 18 19 35]


In [3]:
np.where(x1>40) # return index

(array([3, 4]),)

In [4]:
np.where(x1%2==0,"Even","Odd")

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Odd', 'Odd', 'Even',
       'Even', 'Odd', 'Odd'], dtype='<U4')

In [5]:
l2=[[1,21,3,5],[41,5,1,67],[71,8,91,77]]
x2=np.array(l2)
print(x2)

[[ 1 21  3  5]
 [41  5  1 67]
 [71  8 91 77]]


In [6]:
np.sort(x2)  #axis=1 row wise sort by default

array([[ 1,  3,  5, 21],
       [ 1,  5, 41, 67],
       [ 8, 71, 77, 91]])

In [7]:
np.sort(x2,axis=0) # axis=0 col wise

array([[ 1,  5,  1,  5],
       [41,  8,  3, 67],
       [71, 21, 91, 77]])